---
- hosts: all
  become: yes
  vars:
    - conf_path: "/etc/ssh/sshd_config"
  tasks:
    - name: modify ssh_config
      replace:
        dest: "{{ conf_path }}"
        regexp: "^PasswordAuthentication no"
        replace: "PasswordAuthentication yes"
      notify: restart sshd

  handlers:
    - name: restart sshd
      systemd:
        state: restarted
        name: sshd

